SET search_path TO aman, public;
INSERT INTO sites(id,name,location) VALUES (1,'Gas Processing Plant','Fahud, Oman'),(2,'Pump Station','Nimr, Oman') ON CONFLICT DO NOTHING;
INSERT INTO templates(id,name,site_type) VALUES (1,'Pump station checklist','Pump station'),(2,'Fire safety walk-through','All sites'),(3,'Pressure vessel visual check','Gas processing') ON CONFLICT DO NOTHING;
INSERT INTO questions(template_id,text,position)
SELECT 1, text, position FROM unnest(ARRAY['Is the work area free from spills and obstructions?','Are pump guards secure and undamaged?','Are pressure gauges readable and within operating limits?','Are seals and pipe connections free from visible leaks?','Is the emergency stop accessible and labeled?','Are vibration and noise levels normal?','Are electrical cables and earthing visually intact?','Is required PPE available and being worn?','Is the maintenance log current?']) WITH ORDINALITY AS q(text,position) ON CONFLICT DO NOTHING;
INSERT INTO questions(template_id,text,position)
SELECT 2, text, position FROM unnest(ARRAY['Are escape routes clear and marked?','Are extinguishers accessible and within inspection date?','Are fire doors unobstructed and able to close?','Are alarm call points visible and accessible?','Are combustible materials stored safely?','Are assembly points clearly signposted?','Are hydrants and hose reels accessible?','Are hot-work permits current where applicable?','Is emergency lighting visually operational?']) WITH ORDINALITY AS q(text,position) ON CONFLICT DO NOTHING;
INSERT INTO questions(template_id,text,position)
SELECT 3, text, position FROM unnest(ARRAY['Is the vessel identification plate legible?','Is the vessel exterior free from visible corrosion?','Are supports and anchor bolts intact?','Are pressure indicators readable?','Are relief devices tagged and unobstructed?','Are flanges and connections free from leaks?','Is insulation intact and dry?','Is access to isolation valves clear?','Is the inspection certification current?']) WITH ORDINALITY AS q(text,position) ON CONFLICT DO NOTHING;
