import type { TranslationKey } from "./en";
export const ar: Record<TranslationKey, string> = {
  home: "الرئيسية",
  inspections: "الفحوصات",
  incidents: "البلاغات",
  settings: "الإعدادات",
  appTag: "سلامة الموقع، ببساطة",
  welcome: "نوبة عمل أكثر أماناً تبدأ هنا.",
  loginSubtitle: "موقعك. فريقك. عودة آمنة للجميع.",
  email: "البريد الإلكتروني",
  password: "كلمة المرور",
  signIn: "تسجيل الدخول",
  demoAccounts: "حسابات تجريبية",
  demoPassword: "كلمة المرور: AmanDemo2026!",
  goodMorning: "مرحباً بعودتك",
  overview: "نظرة على الموقع",
  today: "اليوم",
  openIncidents: "بلاغات مفتوحة",
  inspectionsToday: "فحوصات اليوم",
  failed: "غير مستوفٍ",
  attention: "يحتاج إلى متابعة",
  activity: "آخر الأنشطة",
  viewAll: "عرض الكل",
  trend: "اتجاه البلاغات",
  lastWeek: "آخر ٧ أيام",
  reports: "بلاغات",
  newReport: "بلاغ جديد",
  newInspection: "بدء فحص",
  reportIncident: "تسجيل بلاغ",
  newSubtitle: "ملاحظة صغيرة تصنع موقعاً أكثر أماناً.",
  all: "الكل",
  in_progress: "قيد التنفيذ",
  completed: "مكتمل",
  open: "مفتوح",
  closed: "مغلق",
  low: "منخفض",
  medium: "متوسط",
  high: "مرتفع",
  critical: "حرج",
  pass: "مستوفٍ",
  fail: "غير مستوفٍ",
  na: "لا ينطبق",
  search: "البحث في التقارير…",
  noReports: "لا توجد تقارير",
  noReportsHint: "ستظهر التقارير الجديدة هنا.",
  retry: "إعادة المحاولة",
  loading: "جارٍ التحميل",
  template: "نموذج الفحص",
  site: "الموقع",
  equipment: "اسم المعدة",
  equipmentPlaceholder: "مثال: مضخة النقل P-101",
  start: "بدء قائمة الفحص",
  question: "سؤال",
  of: "من",
  notes: "ملاحظات الفحص",
  notesPlaceholder: "صف ما يحتاج إلى متابعة…",
  addPhoto: "إضافة صورة",
  camera: "التقاط صورة",
  gallery: "اختيار من المكتبة",
  next: "التالي",
  back: "رجوع",
  review: "مراجعة الفحص",
  submitInspection: "إرسال الفحص",
  summary: "ملخص الفحص",
  checks: "بنود",
  title: "العنوان",
  titlePlaceholder: "ماذا لاحظت؟",
  severity: "درجة الخطورة",
  category: "الفئة",
  description: "الوصف",
  descriptionPlaceholder: "صف الملاحظة والموقع والإجراء المتخذ…",
  photos: "الصور",
  suggestAI: "اقتراح بالذكاء الاصطناعي",
  aiNote: "قد تكون اقتراحات الذكاء الاصطناعي خاطئة. يرجى المراجعة.",
  aiConsent: "يُرسل الوصف إلى Anthropic فقط عند طلب اقتراح.",
  apply: "تطبيق",
  dismiss: "تجاهل",
  submitIncident: "إرسال البلاغ",
  saved: "تم حفظ التقرير",
  savedHint: "ملاحظتك تساعد الجميع على العمل بأمان.",
  backHome: "العودة للرئيسية",
  profile: "الملف الشخصي",
  appearance: "المظهر",
  system: "النظام",
  light: "فاتح",
  dark: "داكن",
  language: "اللغة",
  english: "English",
  arabic: "العربية",
  signOut: "تسجيل الخروج",
  demoNote:
    "تطبيق تجريبي فقط. جميع السجلات بيانات نموذجية ولا تحتوي على بيانات شركة حقيقية. ليس نظاماً للاستجابة للطوارئ.",
  offline: "غير متصل",
  pending: "تقارير بانتظار المزامنة",
  syncing: "جارٍ مزامنة التقارير…",
  allSynced: "تمت المزامنة",
  syncNow: "مزامنة الآن",
  syncFailed: "تحتاج المزامنة إلى متابعة. تقاريرك محفوظة على هذا الجهاز.",
  assignedTo: "المسؤول",
  unassigned: "غير معين",
  timeline: "سجل المتابعة",
  reportedBy: "مقدم البلاغ",
  status: "الحالة",
  assign: "تعيين",
  close: "إغلاق البلاغ",
  cancel: "إلغاء",
  save: "حفظ",
  required: "أكمل جميع الحقول المطلوبة.",
  failNote: "أضف ملاحظة لكل بند غير مستوفٍ.",
  choose: "اختر",
  photoLimit: "يمكنك إرفاق أربع صور كحد أقصى.",
  photoPermission: "اسمح بالوصول للكاميرا أو الصور من إعدادات الجهاز.",
  queued: "محفوظ على هذا الجهاز",
  details: "تفاصيل التقرير",
  safetyPulse: "مؤشر السلامة",
  shiftNote: "كل ملاحظة مهمة.",
  siteScope: "موقعك",
  allSites: "جميع المواقع",
  quickActions: "اتخذ إجراءً",
  inspectHint: "أكمل قائمة فحص الموقع",
  incidentHint: "سجل خطراً أو حادثاً وشيكاً",
  connected: "متصل",
  team: "الفريق المقترح",
  remove: "حذف",
  edit: "تعديل",
  sessionExpired: "سجل الدخول مجدداً لمزامنة تقاريرك المحفوظة.",
  signOutPending:
    "تبقى التقارير المعلقة على هذا الجهاز وتتاح عند تسجيل الدخول بهذا الحساب مرة أخرى.",
  error: "حدث خطأ",
  refresh: "تحديث",
  questionFallback: "سؤال الفحص",
  photoUnavailable: "الصورة غير متاحة دون اتصال",
  invalidServer: "تعذر الوصول للخادم. تحقق من الاتصال.",
  demo: "مساحة تجريبية",
  clear: "مسح",
  changeStatus: "تغيير الحالة",
  chooseAssignee: "اختر عضواً من الفريق",
  noChanges: "لا توجد تغييرات",
  reportCreated: "تم إنشاء البلاغ",
  statusChanged: "تم تغيير الحالة إلى",
  reportAssigned: "تم تعيين البلاغ",
  assignmentRemoved: "تم إلغاء التعيين",
  checklist: "قائمة الفحص",
  safety: "السلامة",
  day: "يوم",
  savedOffline: "تم الحفظ دون اتصال. ستتم المزامنة عند الاتصال.",
  cached: "عرض البيانات المحفوظة",
  permissionHint: "اختر مصدر الصورة",
  closeViewer: "إغلاق الصورة",
  progress: "التقدم",
  total: "الإجمالي",
  showPassword: "إظهار كلمة المرور",
  hidePassword: "إخفاء كلمة المرور",
  signingIn: "جارٍ تسجيل الدخول…",
  saving: "جارٍ الحفظ…",
  account: "الحساب",
  about: "حول أمان",
  version: "الإصدار 1.0.0",
  filter: "تصفية",
  photoTooLarge: "اختر صورة أصغر من ٥ ميغابايت.",
  noTemplates: "اتصل مرة واحدة لتنزيل قوائم الفحص.",
  initialOffline: "سجل الدخول عبر الإنترنت مرة واحدة قبل الاستخدام دون اتصال.",
  refreshHint: "اسحب للأسفل للتحديث",
  continue: "متابعة",
  inspectionReady: "جاهز للإرسال",
  reviewHint: "راجع ملاحظاتك قبل الإرسال.",
  aiSuggestion: "اقتراح الذكاء الاصطناعي",
  photoCount: "مرفقة",
  worker: "عامل",
  supervisor: "مشرف",
  admin: "مسؤول",
  equipmentCategory: "المعدات",
  housekeepingCategory: "ترتيب الموقع",
  electricalCategory: "الكهرباء",
  fireCategory: "السلامة من الحريق",
  otherCategory: "أخرى",
  createdAt: "تاريخ الإنشاء",
  noActivity: "ملاحظتك التالية تبدأ هنا.",
  syncDetails: "الاتصال والمزامنة",
  reportCount: "التقارير",
  reportSubmitted: "تم إرسال التقرير",
  siteReady: "جاهز لجولتك القادمة",
  inspectionsHint: "فحوصات منتظمة. عمليات أكثر أماناً.",
  incidentsHint: "لاحظه. بلّغ عنه. عالجه.",
  settingsHint: "اضبط أمان بما يناسبك.",
  offlineHint: "تُحفظ التقارير على هذا الجهاز حتى تعود للاتصال.",
  onlineRequired: "اتصل بالإنترنت لإجراء هذا التغيير.",
};
