export const en = {
  home: "Home",
  inspections: "Inspections",
  incidents: "Incidents",
  settings: "Settings",
  appTag: "FIELD SAFETY, SIMPLIFIED",
  welcome: "A safer shift starts here.",
  loginSubtitle: "Your site. Your team. Everyone home safely.",
  email: "Email address",
  password: "Password",
  signIn: "Sign in",
  demoAccounts: "Demo accounts",
  demoPassword: "Password: AmanDemo2026!",
  goodMorning: "Welcome back",
  overview: "Site overview",
  today: "Today",
  openIncidents: "Open incidents",
  inspectionsToday: "Inspections today",
  failed: "Failed",
  attention: "Needs attention",
  activity: "Recent activity",
  viewAll: "View all",
  trend: "Incident trend",
  lastWeek: "Last 7 days",
  reports: "reports",
  newReport: "New report",
  newInspection: "Start inspection",
  reportIncident: "Report incident",
  newSubtitle: "A small observation makes a safer site.",
  all: "All",
  in_progress: "In progress",
  completed: "Completed",
  open: "Open",
  closed: "Closed",
  low: "Low",
  medium: "Medium",
  high: "High",
  critical: "Critical",
  pass: "Pass",
  fail: "Fail",
  na: "N/A",
  search: "Search reports…",
  noReports: "No reports to show",
  noReportsHint: "New reports will appear here.",
  retry: "Try again",
  loading: "Loading",
  template: "Checklist template",
  site: "Site",
  equipment: "Equipment name",
  equipmentPlaceholder: "e.g. Transfer pump P-101",
  start: "Start checklist",
  question: "Question",
  of: "of",
  notes: "Observation notes",
  notesPlaceholder: "Describe what needs attention…",
  addPhoto: "Add photo",
  camera: "Take photo",
  gallery: "Choose from library",
  next: "Next",
  back: "Back",
  review: "Review inspection",
  submitInspection: "Submit inspection",
  summary: "Inspection summary",
  checks: "checks",
  title: "Title",
  titlePlaceholder: "What did you observe?",
  severity: "Severity",
  category: "Category",
  description: "Description",
  descriptionPlaceholder:
    "Describe the observation, location and action taken…",
  photos: "Photos",
  suggestAI: "Suggest with AI",
  aiNote: "AI suggestions can be wrong. Please review.",
  aiConsent:
    "The description is sent to Anthropic only when you request a suggestion.",
  apply: "Apply",
  dismiss: "Dismiss",
  submitIncident: "Submit report",
  saved: "Report saved",
  savedHint: "Your observation helps everyone work safely.",
  backHome: "Back to home",
  profile: "Profile",
  appearance: "Appearance",
  system: "System",
  light: "Light",
  dark: "Dark",
  language: "Language",
  english: "English",
  arabic: "العربية",
  signOut: "Sign out",
  demoNote:
    "Demo only. All records are sample data, with no real company data. Not an emergency response system.",
  offline: "Offline",
  pending: "reports waiting to sync",
  syncing: "Syncing reports…",
  allSynced: "All synced",
  syncNow: "Sync now",
  syncFailed: "Sync needs attention. Your reports are saved on this device.",
  assignedTo: "Assigned to",
  unassigned: "Unassigned",
  timeline: "Timeline",
  reportedBy: "Reported by",
  status: "Status",
  assign: "Assign",
  close: "Close report",
  cancel: "Cancel",
  save: "Save",
  required: "Complete all required fields.",
  failNote: "Add a note for each failed check.",
  choose: "Choose",
  photoLimit: "You can attach up to four photos.",
  photoPermission: "Allow camera or photo access in device settings.",
  queued: "Saved on this device",
  details: "Report details",
  safetyPulse: "Safety pulse",
  shiftNote: "Every observation counts.",
  siteScope: "Your site",
  allSites: "All sites",
  quickActions: "Take action",
  inspectHint: "Work through a site checklist",
  incidentHint: "Capture a hazard or near miss",
  connected: "Connected",
  team: "Suggested team",
  remove: "Remove",
  edit: "Edit",
  sessionExpired: "Please sign in again to sync your saved reports.",
  signOutPending:
    "Reports waiting to sync stay on this device and are available when this account signs in again.",
  error: "Something went wrong",
  refresh: "Refresh",
  questionFallback: "Checklist question",
  photoUnavailable: "Photo unavailable offline",
  invalidServer: "Cannot reach the server. Check your connection.",
  demo: "DEMO WORKSPACE",
  clear: "Clear",
  changeStatus: "Change status",
  chooseAssignee: "Choose a team member",
  noChanges: "No changes",
  reportCreated: "Report created",
  statusChanged: "Status changed to",
  reportAssigned: "Report assigned",
  assignmentRemoved: "Assignment removed",
  checklist: "Checklist",
  safety: "Safety",
  day: "day",
  savedOffline: "Saved offline. It will sync when you reconnect.",
  cached: "Showing saved data",
  permissionHint: "Choose a photo source",
  closeViewer: "Close photo",
  progress: "Progress",
  total: "Total",
  showPassword: "Show password",
  hidePassword: "Hide password",
  signingIn: "Signing in…",
  saving: "Saving…",
  account: "Account",
  about: "About Aman",
  version: "Version 1.0.0",
  filter: "Filter",
  photoTooLarge: "Choose an image smaller than 5 MB.",
  noTemplates: "Connect once to download your site checklists.",
  initialOffline: "Sign in online once before using offline mode.",
  refreshHint: "Pull down to refresh",
  continue: "Continue",
  inspectionReady: "Ready to submit",
  reviewHint: "Review your observations before submitting.",
  aiSuggestion: "AI suggestion",
  photoCount: "attached",
  worker: "Worker",
  supervisor: "Supervisor",
  admin: "Admin",
  equipmentCategory: "Equipment",
  housekeepingCategory: "Housekeeping",
  electricalCategory: "Electrical",
  fireCategory: "Fire safety",
  otherCategory: "Other",
  createdAt: "Created",
  noActivity: "Your next observation starts here.",
  syncDetails: "Offline & sync",
  reportCount: "Reports",
  reportSubmitted: "Report submitted",
  siteReady: "Ready for your next round",
  inspectionsHint: "Consistent checks. Safer operations.",
  incidentsHint: "See it. Report it. Resolve it.",
  settingsHint: "Make Aman work for you.",
  offlineHint: "Reports are saved securely on this device until you reconnect.",
  onlineRequired: "Connect to the internet to make this change.",
};
export type TranslationKey = keyof typeof en;
